//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateAuth.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountUserInfo
    {
        public string UserId { get; set; }
        public int UserInfoId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
